In [1]:
import pandas as pd
import numpy as np

In [2]:
file= open('A.txt','r',encoding = 'utf-8')

In [3]:
data=file.read()

In [4]:
import re

In [5]:
pattern = '\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}\s\w{2}\s-\s'

In [6]:
msg = re.split(pattern,data)

In [7]:
dates = re.findall(pattern,data)

In [8]:
Date_P = '\d{1,2}/\d{1,2}/\d{2,4}'

In [9]:
date=re.findall(Date_P,data)

In [10]:
time = '\d{1,2}:\d{2}'

In [11]:
TIME=re.findall(time,data)

In [12]:
TIME

['10:49',
 '10:49',
 '10:50',
 '10:51',
 '10:51',
 '10:51',
 '10:51',
 '10:51',
 '10:51',
 '10:51',
 '10:52',
 '10:52',
 '10:52',
 '11:30',
 '10:52',
 '10:53',
 '10:53',
 '10:53',
 '10:25',
 '10:26',
 '10:27',
 '10:27',
 '10:27',
 '10:27',
 '10:28',
 '10:28',
 '10:28',
 '10:28',
 '10:28',
 '10:29',
 '10:29',
 '10:29',
 '10:29',
 '10:32',
 '10:32',
 '10:32',
 '10:33',
 '10:33',
 '10:33',
 '10:33',
 '10:34',
 '10:34',
 '10:34',
 '10:34',
 '10:34',
 '10:34',
 '10:57',
 '10:57',
 '10:58',
 '10:59',
 '11:00',
 '11:00',
 '11:00',
 '11:00',
 '11:01',
 '11:01',
 '11:01',
 '11:07',
 '11:08',
 '11:10',
 '11:11',
 '11:11',
 '11:12',
 '11:12',
 '11:13',
 '11:13',
 '11:14',
 '11:14',
 '11:14',
 '11:14',
 '11:14',
 '11:14',
 '11:15',
 '11:15',
 '11:15',
 '11:16',
 '11:16',
 '11:16',
 '11:16',
 '10:32',
 '10:32',
 '10:32',
 '10:33',
 '10:33',
 '10:33',
 '10:33',
 '10:33',
 '10:33',
 '10:33',
 '10:34',
 '10:34',
 '10:34',
 '10:34',
 '10:34',
 '10:35',
 '10:35',
 '10:36',
 '10:36',
 '10:36',
 '10:36',
 '10:36',
 '10:36',
 '10:36',
 '10:36',
 '10:37',
 '10:37',
 '10:38',
 '10:38',
 '10:38',
 '10:38',
 '10:39',
 '10:39',
 '10:39',
 '10:39',
 '10:40',
 '10:40',
 '10:40',
 '10:41',
 '10:41',
 '7:34',
 '2:30',
 '6:51',
 '5:49',
 '4:01',
 '4:01',
 '4:03',
 '2:44',
 '2:45',
 '2:48',
 '3:28',
 '3:29',
 '3:31',
 '3:32',
 '3:32',
 '3:32',
 '9:56',
 '9:57',
 '9:57',
 '9:57',
 '9:58',
 '9:58',
 '9:58',
 '9:58',
 '9:58',
 '9:58',
 '9:59',
 '9:59',
 '9:59',
 '9:59',
 '9:59',
 '10:00',
 '10:00',
 '10:00',
 '10:00',
 '10:01',
 '10:01',
 '10:01',
 '10:01',
 '10:01',
 '10:01',
 '10:02',
 '10:02',
 '10:02',
 '10:02',
 '10:02',
 '10:02',
 '10:02',
 '10:02',
 '10:02',
 '6:24',
 '10:10',
 '10:14',
 '10:20',
 '10:23',
 '10:27',
 '10:28',
 '10:28',
 '10:28',
 '10:28',
 '10:29',
 '10:29',
 '10:45',
 '10:45',
 '2:26',
 '8:34',
 '8:27',
 '9:37',
 '9:37',
 '9:37',
 '9:37',
 '10:13',
 '10:13',
 '10:13',
 '10:14',
 '10:14',
 '10:14',
 '10:14',
 '7:44',
 '7:44',
 '7:44',
 '7:44',
 '9:37',
 '7:54',
 '9:09',
 '9:11',
 '9:11',
 '9:12',
 '9:12',
 '9:12',
 '9:12',
 '9:13',
 '9:13',
 '9:14',
 '9:14',
 '9:14',
 '9:15',
 '8:25',
 '8:26',
 '8:26',
 '8:26',
 '8:26',
 '10:19',
 '10:52',
 '10:52',
 '10:52',
 '10:52',
 '10:52',
 '10:52',
 '10:52',
 '9:20',
 '9:20',
 '9:20',
 '9:20',
 '9:20',
 '9:20',
 '9:20',
 '9:20',
 '9:20',
 '9:20',
 '9:20',
 '9:20',
 '9:20',
 '9:20',
 '9:20',
 '9:20',
 '9:20',
 '9:20',
 '9:20',
 '9:20',
 '9:20',
 '9:20',
 '9:20',
 '9:20',
 '9:25',
 '9:26',
 '9:26',
 '9:26',
 '9:26',
 '9:27',
 '9:27',
 '9:30',
 '9:31',
 '9:31',
 '9:31',
 '9:32',
 '9:32',
 '9:32',
 '9:33',
 '9:33',
 '9:36',
 '9:36',
 '9:36',
 '9:37',
 '9:39',
 '9:39',
 '9:39',
 '9:40',
 '9:40',
 '9:41',
 '9:41',
 '9:42',
 '9:42',
 '9:42',
 '9:42',
 '10:44',
 '10:45',
 '10:45',
 '10:45',
 '11:16',
 '11:16',
 '11:28',
 '11:29',
 '11:31',
 '11:31',
 '11:31',
 '11:31',
 '11:31',
 '11:32',
 '11:32',
 '11:32',
 '11:32',
 '11:32',
 '11:32',
 '11:32',
 '11:32',
 '11:32',
 '11:32',
 '11:32',
 '7:06',
 '7:06',
 '7:06',
 '7:06',
 '7:07',
 '8:28',
 '8:28',
 '8:39',
 '8:40',
 '8:41',
 '8:41',
 '8:41',
 '8:41',
 '8:27',
 '3:36',
 '3:15',
 '8:32',
 '2:05',
 '12:53',
 '12:55',
 '12:55',
 '12:55',
 '12:56',
 '12:56',
 '12:56',
 '12:56',
 '12:57',
 '1:00',
 '1:00',
 '1:00',
 '1:00',
 '1:01',
 '1:01',
 '1:01',
 '1:01',
 '1:03',
 '1:03',
 '1:03',
 '1:03',
 '1:03',
 '1:03',
 '1:03',
 '1:04',
 '1:04',
 '1:04',
 '1:04',
 '1:05',
 '1:05',
 '1:05',
 '1:07',
 '1:07',
 '1:08',
 '1:08',
 '1:08',
 '1:08',
 '1:09',
 '1:09',
 '1:09',
 '1:10',
 '1:10',
 '1:10',
 '1:10',
 '1:10',
 '1:10',
 '1:10',
 '1:10',
 '1:10',
 '1:10',
 '1:11',
 '1:11',
 '1:11',
 '1:12',
 '1:12',
 '1:12',
 '1:12',
 '1:12',
 '1:12',
 '1:13',
 '1:13',
 '1:13',
 '1:13',
 '1:13',
 '1:13',
 '1:13',
 '1:14',
 '1:15',
 '1:15',
 '1:16',
 '1:16',
 '1:16',
 '1:16',
 '2:18',
 '6:17',
 '6:18',
 '6:19',
 '9:03',
 '4:40',
 '8:50',
 '10:13',
 '10:14',
 '3:12',
 '3:13',
 '3:13',
 '3:13',
 '3:17',
 '3:59',
 '3:59',
 '3:20',
 '3:21',
 '3:23',
 '3:23',
 '3:23',
 '3:23',
 '3:24',
 '3:36',
 '3:37',
 '3:37',
 '3:37',
 '3:51',
 '3:51',
 '3:52',
 '3:52',
 '3:52',
 '3:52',
 '3:52',
 '3:53',
 '3:53',
 '3:53',
 '3:54',
 '3:54',
 '3:54',
 '3:54',
 '3:54',
 '3:54',
 '3:54',
 '8:06',
 '1:17',
 '1:17',
 '1:18',
 '10:34',
 '6:00',
 '3:34',
 '8:11',
 '8:11',
 '8:15',
 '8:33',
 '8:34',
 '8:34',
 '8:35',
 '8:35',
 '8:36',
 '8:37',
 '8:37',
 '8:38',
 '8:39',
 '9:30',
 '10:05',
 '10:05',
 '10:05',
 '10:05',
 '10:20',
 '10:20',
 '10:20',
 '10:20',
 '10:21',
 '10:21',
 '10:21',
 '10:22',
 '10:22',
 '10:22',
 '10:23',
 '10:23',
 '10:24',
 '10:24',
 '10:26',
 '10:26',
 '10:30',
 '10:30',
 '10:38',
 '10:38',
 '10:51',
 '12:02',
 '12:02',
 '12:02',
 '12:04',
 '12:05',
 '12:05',
 '12:05',
 '12:10',
 '12:10',
 '12:11',
 '12:11',
 '12:14',
 '12:14',
 '12:14',
 '12:15',
 '12:16',
 '12:16',
 '12:16',
 '12:16',
 '12:16',
 '12:16',
 '12:16',
 '12:40',
 '8:57',
 '5:23',
 '5:23',
 '5:33',
 '5:33',
 '5:33',
 '5:33',
 '5:35',
 '5:35',
 '5:39',
 '5:39',
 '5:41',
 '5:42',
 '5:42',
 '5:42',
 '6:22',
 '6:27',
 '5:40',
 '5:56',
 '9:57',
 '11:58',
 '11:58',
 '11:58',
 '11:59',
 '12:00',
 '12:00',
 '12:00',
 '12:00',
 '12:01',
 '12:01',
 '12:01',
 '12:01',
 '12:03',
 '12:03',
 '12:03',
 '12:03',
 '12:03',
 '12:04',
 '12:05',
 '12:05',
 '12:05',
 '12:05',
 '12:06',
 '12:06',
 '12:06',
 '12:06',
 '12:07',
 '12:08',
 '12:08',
 '12:08',
 '12:09',
 '12:09',
 '12:09',
 '12:09',
 '12:09',
 '12:09',
 '12:09',
 '12:09',
 '12:09',
 '8:34',
 '8:34',
 '8:34',
 '8:35',
 '8:35',
 '8:35',
 '8:35',
 '8:35',
 '8:35',
 '8:35',
 '8:35',
 '8:35',
 '8:36',
 '8:36',
 '8:36',
 '8:36',
 '8:36',
 '8:36',
 '8:37',
 '8:37',
 '8:37',
 '8:37',
 '8:37',
 '8:46',
 '5:57',
 '10:25',
 '11:36',
 '11:36',
 '11:41',
 '3:48',
 '10:59',
 '9:52',
 '4:24',
 '8:09',
 '1:05',
 '10:44',
 '10:01',
 '9:35',
 '9:30',
 '10:50',
 '10:50',
 '8:08',
 '9:51',
 '9:57',
 '8:35',
 '8:35',
 '11:20',
 '11:50',
 '11:52',
 '12:12',
 '12:17',
 '2:22',
 '8:32',
 '8:32',
 '8:32',
 '8:38',
 '11:56',
 '12:03',
 '12:03',
 '12:03',
 '12:04',
 '12:09',
 '12:09',
 '12:09',
 '12:09',
 '12:09',
 '12:09',
 '12:10',
 '12:10',
 '12:10',
 '12:10',
 '12:10',
 '12:10',
 '12:10',
 '12:11',
 '12:12',
 '1:48',
 '1:48',
 '1:48',
 '1:48',
 '1:49',
 '6:16',
 '11:35',
 '11:35',
 '11:35',
 '11:35',
 '11:35',
 '11:35',
 '11:35',
 '11:36',
 '11:36',
 '11:51',
 '11:51',
 '7:42',
 '7:48',
 '7:59',
 '9:11',
 '9:33',
 '9:33',
 '9:42',
 '9:53',
 '9:52',
 '9:53',
 '9:53',
 '9:53',
 '9:53',
 '9:54',
 '9:54',
 '9:54',
 '9:55',
 '9:56',
 '9:56',
 '9:56',
 '9:56',
 '9:56',
 '9:57',
 '9:57',
 '9:57',
 '9:57',
 '9:58',
 '9:58',
 '9:58',
 '9:58',
 '9:58',
 '9:58',
 '10:01',
 '8:47',
 '8:47',
 '8:58',
 '8:58',
 '9:26',
 '9:27',
 '9:27',
 '10:08',
 '10:34',
 '10:35',
 '10:35',
 '10:35',
 '10:35',
 '10:36',
 '10:40',
 '10:40',
 '10:40',
 '8:51',
 '8:51',
 '8:52',
 '8:31',
 '8:40',
 '8:47',
 '8:47',
 '8:47',
 '8:47',
 '8:49',
 '8:53',
 '8:54',
 '8:54',
 '9:10',
 '9:11',
 '9:11',
 '9:11',
 '9:11',
 '9:11',
 '9:12',
 '9:12',
 '9:12',
 '9:12',
 '9:12',
 '9:12',
 '9:12',
 '9:12',
 '9:14',
 '9:14',
 '9:14',
 '9:14',
 '9:14',
 '9:15',
 '9:15',
 '9:16',
 '9:18',
 '9:18',
 '9:18',
 '9:18',
 '9:18',
 '9:19',
 '9:19',
 '9:19',
 '9:19',
 '9:37',
 '9:37',
 '9:37',
 '9:38',
 '9:38',
 '9:38',
 '9:39',
 '9:39',
 '9:39',
 '9:41',
 '9:41',
 '9:42',
 '9:42',
 '9:44',
 '9:46',
 '9:48',
 '9:49',
 '9:49',
 '9:47',
 '9:48',
 '9:48',
 '10:07',
 '10:07',
 '10:07',
 '10:07',
 '10:07',
 '10:08',
 '10:08',
 '10:08',
 '10:08',
 '10:09',
 '11:31',
 '11:31',
 '11:33',
 '6:48',
 '7:39',
 '1:35',
 '1:35',
 '1:40',
 '2:03',
 '2:03',
 '2:03',
 '2:03',
 '2:03',
 '2:03',
 '2:03',
 '2:03',
 '2:03',
 '2:03',
 '2:03',
 '2:03',
 '2:03',
 '2:03',
 '9:08',
 '9:08',
 '9:08',
 '9:16',
 '9:16',
 '9:16',
 '9:16',
 '9:44',
 '9:44',
 '9:44',
 '9:44',
 '9:44',
 '9:44',
 '2:11',
 '2:11',
 '2:11',
 '2:12',
 '2:12',
 '2:12',
 '2:12',
 '2:13',
 '2:13',
 '2:13',
 '2:13',
 '11:56',
 '11:56',
 '11:56',
 '11:56',
 '11:56',
 '11:57',
 '11:57',
 '11:57',
 '11:57',
 '11:57',
 '11:57',
 '11:57',
 '11:57',
 '11:58',
 '11:58',
 '11:58',
 '11:58',
 '11:58',
 '11:58',
 '11:58',
 '11:58',
 '11:59',
 '11:37',
 '11:37',
 '11:37',
 '11:38',
 '11:38',
 '11:50',
 '11:50',
 '11:51',
 '12:16',
 '12:16',
 '8:01',
 '8:18',
 '8:19',
 '8:19',
 '8:19',
 '8:20',
 '8:20',
 '8:20',
 '8:20',
 '8:21',
 '8:57',
 '8:58',
 '8:58',
 '8:58',
 '4:52',
 '4:52',
 '6:02',
 '6:33',
 '6:38',
 '6:38',
 '6:38',
 '6:38',
 '6:38',
 '6:39',
 '6:39',
 '6:39',
 '6:39',
 '6:39',
 '6:39',
 '6:39',
 '6:39',
 '6:40',
 '6:40',
 '6:40',
 '6:40',
 '6:40',
 '6:40',
 '6:41',
 '6:41',
 '6:41',
 '6:42',
 '6:42',
 '6:42',
 '6:42',
 '6:42',
 '6:42',
 '6:42',
 '12:36',
 '8:26',
 '8:27',
 '8:28',
 '8:28',
 '8:29',
 '9:33',
 '9:33',
 '9:33',
 '9:33',
 '9:33',
 '9:34',
 '9:34',
 '9:34',
 '9:34',
 '9:34',
 '9:35',
 '9:35',
 '9:35',
 '9:35',
 '9:37',
 '2:36',
 '2:36',
 '7:21',
 '7:21',
 '7:22',
 '7:22',
 '7:22',
 '7:22',
 '7:22',
 '7:22',
 '7:22',
 '7:23',
 '7:23',
 '7:23',
 '7:23',
 '7:23',
 '7:24',
 '7:24',
 '7:24',
 '7:24',
 '7:24',
 '7:24',
 '7:24',
 '7:24',
 '7:25',
 '7:25',
 '7:25',
 '7:25',
 '7:25',
 '7:25',
 '7:26',
 '7:26',
 '7:26',
 '7:26',
 '7:26',
 '7:27',
 '7:27',
 '5:03',
 '5:04',
 '5:04',
 '5:05',
 '5:15',
 '5:15',
 '5:15',
 '5:16',
 '5:16',
 '5:16',
 '5:44',
 '7:08',
 '7:08',
 '8:48',
 '9:43',
 '9:45',
 '9:46',
 '9:49',
 '9:50',
 '9:50',
 '10:22',
 '10:23',
 '10:23',
 '10:25',
 '10:25',
 '10:26',
 '10:26',
 '10:26',
 ...]

In [13]:
df = pd.DataFrame({'message':msg})

In [14]:
message = pd.DataFrame({'msg':msg})

In [15]:
DATE = pd.DataFrame({'date':date})

In [16]:
 message['date']=DATE

In [17]:
message

                                                    msg     date
0                                                        12/2/18
1     Messages and calls are end-to-end encrypted. N...  12/2/18
2                             Kuldeep Nagar😊: Ha bhai\n  12/2/18
3            Anurag 2: Accha chal theek hai Karle bat\n  12/2/18
4       Kuldeep Nagar😊: Hao thank you thodi der so ja\n  12/2/18
...                                                 ...      ...
1227  Kuldeep Nagar😊: Ladenge to bhi ghar pata chal ...  7/25/21
1228                              Anurag 2: Wo to hai\n  7/25/21
1229             Anurag 2: To fir message kaise aaya?\n  7/25/21
1230       Kuldeep Nagar😊: Are bc usne kiya new nk se\n  7/25/21
1231                                  Anurag 2: Accha\n  7/25/21

[1232 rows x 2 columns]

In [18]:
Time = pd.DataFrame({'TIME':TIME})

In [19]:
message['Time']=Time

In [20]:
message

                                                    msg     date   Time
0                                                        12/2/18  10:49
1     Messages and calls are end-to-end encrypted. N...  12/2/18  10:49
2                             Kuldeep Nagar😊: Ha bhai\n  12/2/18  10:50
3            Anurag 2: Accha chal theek hai Karle bat\n  12/2/18  10:51
4       Kuldeep Nagar😊: Hao thank you thodi der so ja\n  12/2/18  10:51
...                                                 ...      ...    ...
1227  Kuldeep Nagar😊: Ladenge to bhi ghar pata chal ...  7/25/21  10:35
1228                              Anurag 2: Wo to hai\n  7/25/21  10:42
1229             Anurag 2: To fir message kaise aaya?\n  7/25/21  10:43
1230       Kuldeep Nagar😊: Are bc usne kiya new nk se\n  7/25/21  10:52
1231                                  Anurag 2: Accha\n  7/25/21  11:06

[1232 rows x 3 columns]

In [36]:
formate= '\s\w{2}\s-'

In [37]:
f= re.findall(formate,data)

In [38]:
df=pd.DataFrame({'formate':f})

In [39]:
message['formate']=df

In [40]:
message.head()

                                                 msg     date   Time formate
0                                                     12/2/18  10:49    PM -
1  Messages and calls are end-to-end encrypted. N...  12/2/18  10:49    PM -
2                          Kuldeep Nagar😊: Ha bhai\n  12/2/18  10:50    PM -
3         Anurag 2: Accha chal theek hai Karle bat\n  12/2/18  10:51    PM -
4    Kuldeep Nagar😊: Hao thank you thodi der so ja\n  12/2/18  10:51    PM -

In [41]:
message.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1232 entries, 0 to 1231
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   msg      1232 non-null   object
 1   date     1232 non-null   object
 2   Time     1232 non-null   object
 3   formate  1231 non-null   object
dtypes: object(4)
memory usage: 38.6+ KB

In [42]:
s= message['formate'][0]

In [43]:
s

' PM -'

In [45]:
s.replace(" -","")

' PM'

In [47]:
s=s.replace(" ","")

In [48]:
s

'PM-'

In [49]:
s=s.replace("-","")

In [50]:
s

'PM'

In [51]:
def rep(s):
    l=s
    l=l.replace(" ","")
    l=l.replace("-","")
    return l

In [60]:
message['formate']=message['formate'].apply(rep)

In [61]:
message['formate']=message['formate'].astype(str)

In [62]:
message

,msg,date,Time,formate
0,,12/2/18,10:49,PM
1,Messages and calls are end-to-end encrypted. N...,12/2/18,10:49,PM
2,Kuldeep Nagar😊: Ha bhai\n,12/2/18,10:50,PM
3,Anurag 2: Accha chal theek hai Karle bat\n,12/2/18,10:51,PM
4,Kuldeep Nagar😊: Hao thank you thodi der so ja\n,12/2/18,10:51,PM
...,...,...,...,...
1227,Kuldeep Nagar😊: Ladenge to bhi ghar pata chal ...,7/25/21,10:35,AM
1228,Anurag 2: Wo to hai\n,7/25/21,10:42,AM
1229,Anurag 2: To fir message kaise aaya?\n,7/25/21,10:43,AM
1230,Kuldeep Nagar😊: Are bc usne kiya new nk se\n,7/25/21,10:52,PM
1231,Anurag 2: Accha\n,7/25/21,11:06,nan

In [63]:
message['msg']

0
1       Messages and calls are end-to-end encrypted. N...
2                               Kuldeep Nagar😊: Ha bhai\n
3              Anurag 2: Accha chal theek hai Karle bat\n
4         Kuldeep Nagar😊: Hao thank you thodi der so ja\n
                              ...
1227    Kuldeep Nagar😊: Ladenge to bhi ghar pata chal ...
1228                                Anurag 2: Wo to hai\n
1229               Anurag 2: To fir message kaise aaya?\n
1230         Kuldeep Nagar😊: Are bc usne kiya new nk se\n
1231                                    Anurag 2: Accha\n
Name: msg, Length: 1232, dtype: object

In [84]:
l=message['msg'][3].split(":")

In [85]:
len(l)

2

In [86]:
l

['Anurag 2', ' Accha chal theek hai Karle bat\n']

In [87]:
def rep(s):
    l=s
    l=l.replace("\n","")
    l=l.replace(",","")
    return l

In [93]:
message['msg']=message['msg'].apply(rep)

In [94]:
message.sample(2)

                                             msg     date   Time formate
44              Kuldeep Nagar😊: Ha pata hai meko  12/8/18  10:34      PM
677  Anurag 2: Wo ispe message nhi karenge kabhi  9/30/19   9:54      PM

In [105]:
message['msg']=message['msg'].astype(str)

In [119]:
user=[]
MSG=[]
for i in df['msg']:
    l= re.split('([\w\W]+?):\s',i)
    if l[1:]:
        user.append(l[1])
        MSG.append(l[2])
    else:
        
        user.append("group_msg")
        MSG.append(l[0])
    
    
df['user']=user
df['message']=MSG

In [118]:
df=message

In [ ]:
df=df.drop(columns={'msg'})

In [127]:
df.reset_index()

,index,date,Time,formate,user,message
0,0,12/2/18,10:49,PM,group_msg,
1,1,12/2/18,10:49,PM,group_msg,Messages and calls are end-to-end encrypted. N...
2,2,12/2/18,10:50,PM,Kuldeep Nagar😊,Ha bhai
3,3,12/2/18,10:51,PM,Anurag 2,Accha chal theek hai Karle bat
4,4,12/2/18,10:51,PM,Kuldeep Nagar😊,Hao thank you thodi der so ja
...,...,...,...,...,...,...
1227,1227,7/25/21,10:35,AM,Kuldeep Nagar😊,Ladenge to bhi ghar pata chal jaega
1228,1228,7/25/21,10:42,AM,Anurag 2,Wo to hai
1229,1229,7/25/21,10:43,AM,Anurag 2,To fir message kaise aaya?
1230,1230,7/25/21,10:52,PM,Kuldeep Nagar😊,Are bc usne kiya new nk se
1231,1231,7/25/21,11:06,nan,Anurag 2,Accha